




.build/mini328/src/sketch.cpp : src/sketch.ino
	@mkdir -p .build/mini328/src
	@echo [93msrc/sketch.ino[0m
	@/usr/local/bin/ino preproc -d Leonardo -o $@ $^


all : .build/mini328/src/sketch.cpp
	@true

