




.build/uno-7b9e21ea/src/sketch.cpp : src/sketch.ino
	@mkdir -p .build/uno-7b9e21ea/src
	@echo [93msrc/sketch.ino[0m
	@/usr/local/bin/ino preproc -d Leonardo -o $@ $^


all : .build/uno-7b9e21ea/src/sketch.cpp
	@true

